apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: validator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unpriviledged
subjects:
  - kind: ServiceAccount
    name: validator
    namespace: default
